<?php
$db = new PDO('mysql:host=localhost;dbname=hoerburger;charset=utf8mb4', 'hoerburger', 'hoerburger');

$locations = array("[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[Kopie aus dem Institut de Folclor in Bukarest]", "[ein rumänischer Teilnehmer der Feldforschung]", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Ghizela Suliteanu?", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger", "Felix Hoerburger");

for ($x = 0; $x <= count($locations); $x++) {
	$c = $x+447;
    $sql = "UPDATE songs SET recorded_by='$locations[$x]' WHERE id='$c'";
    $stmt = $db->prepare($sql);
    $stmt->execute();
}
?>